### ISSUE TITLE
travis support

### ISSUE THREAD

**Issue by mre** [mre/fcat#4]
Now that we have some tests (thanks @vbrandl!), we should also set up a proper travis environment that will run the tests after every change.

**Comment by mre** [comment]
Get started here: https://docs.travis-ci.com/

**Comment by vbrandl** [comment]
I will work on this one. I already did that for some of my Rust projects (e.g. https://github.com/vbrandl/nginx-http2-push-generator). I guess we should also upload the binaries for tagged commits?
Since splice is only available on Linux, only the following targets should make sense?

* i686-unknown-linux-gnu
* i686-unknown-linux-musl
* x86_64-unknown-linux-gnu
* x86_64-unknown-linux-musl
* aarch64-unknown-linux-gnu
* arm-unknown-linux-gnueabi
* armv7-unknown-linux-gnueabihf
* mips-unknown-linux-gnu
* mips64-unknown-linux-gnuabi64
* mips64el-unknown-linux-gnuabi64
* mipsel-unknown-linux-gnu
* powerpc-unknown-linux-gnu
* powerpc64-unknown-linux-gnu
* powerpc64le-unknown-linux-gnu
* s390x-unknown-linux-gnu

What about the Android targets? Has anyone tested if fcat works on Android?

**Comment by mre** [comment]
Don't know of anyone who tried on Android yet. TIL travis supports Android builds: https://docs.travis-ci.com/user/languages/android/
